name: kindling
channels:
- pytorch
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- blas=1.0
- brotlipy=0.7.0
- bzip2=1.0.8
- ca-certificates=2022.3.18
- certifi=2021.10.8
- cffi=1.15.0
- charset-normalizer=2.0.4
- cryptography=36.0.0
- cudatoolkit=11.3.1
- ffmpeg=4.3
- freetype=2.11.0
- giflib=5.2.1
- gmp=6.2.1
- gnutls=3.6.15
- idna=3.3
- intel-openmp=2021.4.0
- jpeg=9d
- lame=3.100
- lcms2=2.12
- ld_impl_linux-64=2.35.1
- libffi=3.3
- libgcc-ng=9.3.0
- libgomp=9.3.0
- libiconv=1.15
- libidn2=2.3.2
- libpng=1.6.37
- libstdcxx-ng=9.3.0
- libtasn1=4.16.0
- libtiff=4.2.0
- libunistring=0.9.10
- libuv=1.40.0
- libwebp=1.2.2
- libwebp-base=1.2.2
- lz4-c=1.9.3
- mkl=2021.4.0
- mkl-service=2.4.0
- mkl_fft=1.3.1
- mkl_random=1.2.2
- ncurses=6.3
- nettle=3.7.3
- numpy=1.21.2
- numpy-base=1.21.2
- openh264=2.1.1
- openssl=1.1.1n
- pillow=9.0.1
- pip=21.2.4
- pycparser=2.21
- pyopenssl=22.0.0
- pysocks=1.7.1
- python=3.8.12
- pytorch=1.11.0
- pytorch-mutex=1.0
- readline=8.1.2
- requests=2.27.1
- setuptools=58.0.4
- six=1.16.0
- sqlite=3.38.0
- tk=8.6.11
- torchaudio=0.11.0
- torchvision=0.12.0
- typing_extensions=4.1.1
- urllib3=1.26.8
- wheel=0.37.1
- xz=5.2.5
- zlib=1.2.11
- zstd=1.4.9
- pip:
  - antlr4-python3-runtime==4.8
  - black==22.1.0
  - cfgv==3.3.1
  - click==8.0.4
  - cycler==0.11.0
  - distlib==0.3.4
  - docker-pycreds==0.4.0
  - filelock==3.6.0
  - flake8==4.0.1
  - fonttools==4.31.2
  - gitdb==4.0.9
  - gitpython==3.1.27
  - hydra-core==1.1.1
  - identify==2.4.12
  - importlib-resources==5.4.0
  - isort==5.10.1
  - kiwisolver==1.4.0
  - matplotlib==3.5.1
  - mccabe==0.6.1
  - mypy-extensions==0.4.3
  - nodeenv==1.6.0
  - omegaconf==2.1.1
  - packaging==21.3
  - pathspec==0.9.0
  - pathtools==0.1.2
  - platformdirs==2.5.1
  - pre-commit==2.17.0
  - promise==2.3
  - protobuf==3.19.4
  - psutil==5.9.0
  - pycodestyle==2.8.0
  - pyflakes==2.4.0
  - pyparsing==3.0.7
  - python-dateutil==2.8.2
  - pyyaml==6.0
  - sentry-sdk==1.5.8
  - setproctitle==1.2.2
  - shortuuid==1.0.8
  - smmap==5.0.0
  - termcolor==1.1.0
  - toml==0.10.2
  - tomli==2.0.1
  - virtualenv==20.13.4
  - wandb==0.12.11
  - yaspin==2.1.0
  - zipp==3.7.0
